### ISSUE TITLE
Some question about the paper

### ISSUE THREAD

**Issue by shuosir** [lyh-18/EQVI#8]
Hello, your work is outstanding ！
But I didn’t understand the derivation of acceleration and velocity. You mentioned in the paper that if the directions of acceleration a1 and a2 are inconsistent, it will degenerate to the QVI model. If they are the same, then your model will be used. 
My question is, why can’t I use the QVI model when the acceleration remains constant?

**Comment by lyh-18** [comment]
In QVI model, the acceleration and velocity will be calculated twice: forward 3 frames and backward 3 frames. The results of forward and backward are usually different with each other due to data turbulence. Thus, we directly compute the acceleration and velocity with four frames together by LSE. This will lead to only one exact and more accurate result, if the data conform to the quadratic motion model. However, if the consecutive four frames do not conform to the quadratic motion model, our derivation will fail. A simple solution is to relegate to the original QVI algorithm. But there may be better solutions, e,g., only use central two frames to compute linear result. Our solution is not the best, but could improve the performance of original QVI model. I think more better ways are expected to occur.

**Comment by shuosir** [comment]
Thanks for your answer！
I still have some questions. When the movement completely conforms to the quadratic model, will the acceleration calculated by QVI be different for the two times? After all, the assumption of QVI is constant acceleration. Then the acceleration calculated through the first three frames and the acceleration calculated in the next three frames should be consistent.

**Comment by lyh-18** [comment]
If the four points exactly fall in the quadratic motion model, the result of ours will be the same as QVI. However, in real cases, it is nearly impossible for every four points exactly fall in a quadratic line. In QVI, the forward and backward results are further blended into one value. We do not blend two different values into one, but directly derive the numerical one.

**Comment by shuosir** [comment]
In other words, the results that conform to the quadratic motion model and those that do not conform to the quadratic motion model will degenerate into QVI?

**Comment by lyh-18** [comment]
You can understand in this way. However, in the context of " conform to the quadratic motion model", it means the four data points are **perfectly** fitted in the quadratic equation, which in real scenarios is nearly impossible.
